### PR TITLE
#8: Methods in TypedGR<T> should require correct field names and operators

### PR DESCRIPTION
**Pull request by knikolov-nuvolo**
#8: Methods in TypedGR<T> should require correct field names and operators

### Modifications: 

- Added `Override<TBase, TOverride>` type so I can change method signatures.
- Added `QueryOperator` type to list all available operators.
- Modified `TypedGR<T>` type to override method signatures. Use `keyof T` instead of `string` for arguments that accept only field names. Use `QueryOperator` type instead of `string` for the "operator" argument in `addQuery()`.
- Changed the declarations of the other generic classes in `util` to types. If they are classes, then TypeScript won't complain if you try to create an object (e.g. `new ReferenceGlideElement()`). But there are no actual classes and this will fail at run-time.
- Split code from `util/index.d.ts` into mutliple files.

### Breaking Changes:

- Unfortunately, now you cannot cast between `TypedGR<T>` and `GlideRecord` directly. Types do not match, since `TypedGR<T>` has different signature for some of the methods.
To cast from `GlideRecord` to `TypedGR<T>` you need to cast to `unknown` first (see Example 1, line 5).
Visual Studio Code provides a quick fix for this, and can be automatically resolved with a single click: 
image

### Examples

1. Compile time validation:
image

2. IntelliSense - fields:
image

3. IntelliSense - query operators:
image

### CODE REVIEW

**Comment by knikolov-nuvolo** [comment]
Changes after feedback from Teams:

- All SNAPI classes that use `GlideRecord` now use `SNAPIGlideRecord`
- All non-SNAPI classes that use `GlideRecord` are now generic 
- The other generic types from `util` are removed. The original non-SNAPI classes are made generic. 
- TypeScript does not allow interface `Test<T> extends T` so I created type `GlideRecordProps<T> = GlideRecord<T> & T` (not sure if the name is descriptive)

Now the same functionality can be applied without any casts. Unfortunately, due to TS limitations, we cannot directly access record fields (line 21):
image

This can be resoved by casting to the new type `GlideRecordProps<T>` (line 5):
image

**Comment by bbarber9** [comment]
@knikolov-nuvolo Let's limit the scope of this PR to the following:
1. Update `GlideRecord` to be generic (great job on that by the way)
2. Update all classes that consume/produce/return `GlideRecord`'s to do so with `GlideRecord<any>`

We can submit future PR's to update how each class' interactions with the generic GlideRecord will work. Some of them might be a little more nuanced. Please let me know if you have any concerns

**Comment by bbarber9** [comment]
@knikolov-nuvolo I posted a question to the TypeScript community and they came back with something that really turned out well for this feature set. I submitted a PR with it and added you as a reviewer. Let me know what you think. #13

**Comment by bbarber9** [comment]
Closing due to these changes being put into #13

**Pull request closed without merging**
